import type { NextPage } from "next";
import Head from "next/head";
import { CSSTransition, TransitionGroup } from "react-transition-group";
// components
import GlobalCSS from "../styles/global.css";
import Main from "../components/Main";
import Footer from "../components/Footer";
import Form from "../components/Form";
import UserList from "../components/UserList";
import { useEffect, useState } from "react";
import AfterForm from "../components/AfterForm";

const Home: NextPage = () => {
  // const [loaded, setLoaded] = useState(false);
  const [completed, setCompleted] = useState(false);
  const [showList, setShowList] = useState(false);
  const [lista, setLista] = useState<JSX.Element>(<p></p>);
  const [ime, setIme] = useState("");
  const [prezime, setPrezime] = useState("");
  const [email, setEmail] = useState("");

  useEffect(() => {
    if (showList) setLista(<UserList setShowList={setShowList} />);
    if (!showList) setLista(<p></p>);
  }, [showList]);

  return (
    <div className="root">
      <GlobalCSS />
      <Head>
        <title>Креативни Универзум</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=5.0, user-scalable=0"
        />
        <link
          rel="icon"
          href="../assets/images/283686990_959947594683977_3047274215746798731_n.jpg"
        />
      </Head>

      {/* <TransitionGroup>
        <CSSTransition
          appear={true}
          timeout={1800}
          classNames="transition"
          unmountOnExit
        >
          <StyledHeader></StyledHeader>
        </CSSTransition>
      </TransitionGroup> */}

      <Main>
        {!completed ? (
          <Form
            ime={ime}
            prezime={prezime}
            email={email}
            setIme={setIme}
            setPrezime={setPrezime}
            setEmail={setEmail}
            setCompleted={setCompleted}
          />
        ) : (
          <AfterForm />
        )}
        <div className="loading">
          <p>Proverite listu cekanja klikom na dugme ispod.</p>
          <button
            onClick={() => {
              setShowList(true);
            }}
          >
            Lista
          </button>
        </div>
        {lista}
        <Footer />
      </Main>
    </div>
  );
};

export default Home;
