import type { NextPage } from "next";
import { useState, useEffect } from "react";
import Head from "next/head";
import {
  CSSTransition,
  SwitchTransition,
  TransitionGroup,
} from "react-transition-group";
// components
import GlobalCSS from "../styles/global.css";
import StyledHeader from "../components/Header";
import TeaserPage from "../components/TeaserPage";
import Main from "../components/Main";

interface prop {
  children: JSX.Element | JSX.Element[] | undefined;
}

const Container = ({ children }: prop) => {
  return <div>{children}</div>;
};

const Home: NextPage = () => {
  // const [explored, setExplored] = useState(false);
  // const [mainItems, setMainItems] = useState<JSX.Element>();

  return (
    <div className="root">
      <GlobalCSS />
      <Head>
        <title>Креативни Универзум</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=5.0, user-scalable=0"
        />
        <link
          rel="icon"
          href="../assets/images/283686990_959947594683977_3047274215746798731_n.jpg"
        />
      </Head>

      <TransitionGroup>
        <CSSTransition
          appear={true}
          timeout={1800}
          classNames="transition"
          unmountOnExit
        >
          <StyledHeader></StyledHeader>
        </CSSTransition>
      </TransitionGroup>

      <Main>
        <TeaserPage />
      </Main>

      <footer className="footer"></footer>
    </div>
  );
};

export default Home;
