import type { NextPage } from "next";
import { useState, useEffect, Children } from "react";
import Head from "next/head";
import {
  CSSTransition,
  TransitionGroup,
  SwitchTransition,
} from "react-transition-group";
// components
import GlobalCSS from "../styles/global.css";
import StyledHeader from "../components/Header";
import HoneycombList from "../components/HoneycombList";
import Main from "../components/Main";

interface prop {
  children: JSX.Element | JSX.Element[] | undefined;
}

const Container = ({ children }: prop) => {
  return <div>{children}</div>;
};

const Home: NextPage = () => {
  const [explored, setExplored] = useState(false);
  const [mainItems, setMainItems] = useState<JSX.Element>();

  useEffect(() => {
    if (explored) {
      setMainItems(
        <Main>
          <HoneycombList />
        </Main>
      );
    } else {
      setMainItems(
        <StyledHeader
          explored={explored}
          setExplored={setExplored}
        ></StyledHeader>
      );
    }
  }, [explored]);

  return (
    <div className="root">
      <GlobalCSS />
      <Head>
        <title>Креативни Универзум</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SwitchTransition mode="out-in">
        <CSSTransition
          key={explored.toString()}
          in={!explored}
          appear={true}
          timeout={1800}
          classNames="transition"
          unmountOnExit
        >
          <Container>{mainItems}</Container>
        </CSSTransition>
      </SwitchTransition>

      <footer className="footer"></footer>
    </div>
  );
};

export default Home;
